export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CLEAR_TODO = 'CLEAR_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const NEWGET_TODO = 'NEWGET_TODO'
export const NEWSET_TODO = 'NEWSET_TODO'